dist: trusty

language: php

branches:
    only:
        - master
        - /^\d+\.\d+$/

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION=3.1.*
        - php: 7.0
          env: SYMFONY_VERSION=3.2.*
        - php: 7.1
          env: SYMFONY_VERSION=3.3.* PHPUNIT_FLAGS="-d xdebug.max_nesting_level=1000 --coverage-clover=build/logs/clover.xml"
        - php: hhvm
        - php: nightly
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/.php_cs.cache

before_install:
    - if [[ "$TRAVIS_PHP_VERSION" != "7.1" && "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini || true; fi
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" "symfony/framework-bundle:${SYMFONY_VERSION}" --dev --no-update; fi;

install: composer update --prefer-source --no-interaction --optimize-autoloader

script:
    - bin/phpunit --debug ${PHPUNIT_FLAGS}
    - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then bin/php-cs-fixer fix --diff --dry-run -v; fi;

after_script:
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml; fi
    - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then composer require "satooshi/php-coveralls:^1.0" && travis_retry php bin/coveralls -v; fi
